version: '3'

services:
    db:
        image: mongo:4.1.8-xenial
        container_name: db
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
          - ./dbdata :/home/node/app/data/db
        networks:
          - app-network

    nodejs:
        image: node:14-alpine
        container_name: nodejs
        build:
            context: .
            dockerfile: api.dockerfile
        restart: unless-stopped
        volumes:
            - ./backend/uploads :/home/node/app/backend/uploads
        ports:
            - 8000:8000
        networks:
            - app-network
        working_dir: /home/node/app/backend/
        links:
            - db

    client:
        image: node:14-alpine
        container_name: client
        build:
            context: .
            dockerfile: client.dockerfile
        restart: unless-stopped
        ports:
            - 3000:3000
        networks:
            - app-network
        working_dir: /home/node/app/front-server/
        command: server.js
        links:
            - webserver

    webserver:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: unless-stopped
        expose: 
            - 8080
        ports:
            - 8080:8080
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - nodejs
        networks:
            - app-network

networks:
    app-network:
        driver: bridge