version: '3'

services:
    db:
        image: mongo:4.1.8-xenial
        container_name: db
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
          - ./dbdata :/home/node/app/data/db
        networks:
          - app-network

    nodejs:
        image: node:14-alpine
        container_name: nodejs
        build:
            context: .
            dockerfile: dockerfile
        restart: unless-stopped
        ports:
            - 8000:8000
        networks:
            - app-network
        links:
            - db


    webserver:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: unless-stopped
        expose: 
            - 8080
        ports:
            - 8080:8080
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - nodejs
        networks:
            - app-network

networks:
    app-network:
        driver: bridge